In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Loading Dataset

In [6]:
df=pd.read_csv('Loan_default.csv')

Preprocessing Dataset

In [7]:
df.head()

LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0  I38PQUQS96   56   85994       50587          520              80   
1  HPSK72WA7R   69   50432      124440          458              15   
2  C1OZ6DPJ8Y   46   84208      129188          451              26   
3  V2KKSFM3UN   32   31713       44799          743               0   
4  EY08JDHTZP   60   20437        9139          633               8   

   NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0               4         15.23        36      0.44   Bachelor's   
1               1          4.81        60      0.68     Master's   
2               3         21.17        24      0.31     Master's   
3               3          7.07        24      0.23  High School   
4               4          6.51        48      0.73   Bachelor's   

  EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0      Full-time      Divorced         Yes           Yes       Other   
1      Full-time       Married          No            No       Other   
2     Unemployed      Divorced         Yes           Yes        Auto   
3      Full-time       Married          No            No    Business   
4     Unemployed      Divorced          No           Yes        Auto   

  HasCoSigner  Default  
0         Yes        0  
1         Yes        0  
2          No        1  
3          No        0  
4          No        0

In [8]:
df.shape

(255347, 18)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   LoanID          255347 non-null  object 
 1   Age             255347 non-null  int64  
 2   Income          255347 non-null  int64  
 3   LoanAmount      255347 non-null  int64  
 4   CreditScore     255347 non-null  int64  
 5   MonthsEmployed  255347 non-null  int64  
 6   NumCreditLines  255347 non-null  int64  
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64  
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object 
 11  EmploymentType  255347 non-null  object 
 12  MaritalStatus   255347 non-null  object 
 13  HasMortgage     255347 non-null  object 
 14  HasDependents   255347 non-null  object 
 15  LoanPurpose     255347 non-null  object 
 16  HasCoSigner     255347 non-null  object 
 17  Default   

In [10]:
#Checking for duplicates
df.duplicated().sum()

np.int64(0)

In [11]:
#Checking for null values
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [12]:
#Dropping useless column
df.drop(columns = ["LoanID"] , inplace = True)

In [13]:
#Checking correlation of numeric columns with default column
numeric_df = df.select_dtypes(include='number')
numeric_df.corr()['Default']

Age              -0.167783
Income           -0.099119
LoanAmount        0.086659
CreditScore      -0.034166
MonthsEmployed   -0.097374
NumCreditLines    0.028330
InterestRate      0.131273
LoanTerm          0.000545
DTIRatio          0.019236
Default           1.000000
Name: Default, dtype: float64

In [14]:
#Dropped column with very low correlation
df.drop(columns = ["LoanTerm"] , inplace = True)

In [15]:
#Checking count of different values in categorical feautures
for col in df.select_dtypes(exclude='number').columns:
    if col == 'Default':
        continue
    print(f"\n🔹 {col}\n")
    print(df.groupby(col)['Default'].value_counts())


🔹 Education

Education    Default
Bachelor's   0          56577
             1           7789
High School  0          55673
             1           8230
Master's     0          56633
             1           6908
PhD          0          56811
             1           6726
Name: count, dtype: int64

🔹 EmploymentType

EmploymentType  Default
Full-time       0          57632
                1           6024
Part-time       0          56484
                1           7677
Self-employed   0          56404
                1           7302
Unemployed      0          55174
                1           8650
Name: count, dtype: int64

🔹 MaritalStatus

MaritalStatus  Default
Divorced       0          74376
               1          10657
Married        0          76433
               1           8869
Single         0          74885
               1          10127
Name: count, dtype: int64

🔹 HasMortgage

HasMortgage  Default
No           0          111909
             1           15761
Yes     

In [16]:
# One Hot Encoding
df_encoded = df.copy()

categorical_cols = df_encoded.select_dtypes(exclude='number').columns

df_encoded = pd.get_dummies(df_encoded, columns=categorical_cols, drop_first=True)

In [17]:
df_encoded.head()

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56   85994       50587          520              80               4   
1   69   50432      124440          458              15               1   
2   46   84208      129188          451              26               3   
3   32   31713       44799          743               0               3   
4   60   20437        9139          633               8               4   

   InterestRate  DTIRatio  Default  Education_High School  ...  \
0         15.23      0.44        0                  False  ...   
1          4.81      0.68        0                  False  ...   
2         21.17      0.31        1                  False  ...   
3          7.07      0.23        0                   True  ...   
4          6.51      0.73        0                  False  ...   

   EmploymentType_Unemployed  MaritalStatus_Married  MaritalStatus_Single  \
0                      False                  False                 False   
1                      False                   True                 False   
2                       True                  False                 False   
3                      False                   True                 False   
4                       True                  False                 False   

   HasMortgage_Yes  HasDependents_Yes  LoanPurpose_Business  \
0             True               True                 False   
1            False              False                 False   
2             True               True                 False   
3            False              False                  True   
4            False               True                 False   

   LoanPurpose_Education  LoanPurpose_Home  LoanPurpose_Other  HasCoSigner_Yes  
0                  False             False               True             True  
1                  False             False               True             True  
2                  False             False              False            False  
3                  False             False              False            False  
4                  False             False              False            False  

[5 rows x 24 columns]

In [18]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   Age                           255347 non-null  int64  
 1   Income                        255347 non-null  int64  
 2   LoanAmount                    255347 non-null  int64  
 3   CreditScore                   255347 non-null  int64  
 4   MonthsEmployed                255347 non-null  int64  
 5   NumCreditLines                255347 non-null  int64  
 6   InterestRate                  255347 non-null  float64
 7   DTIRatio                      255347 non-null  float64
 8   Default                       255347 non-null  int64  
 9   Education_High School         255347 non-null  bool   
 10  Education_Master's            255347 non-null  bool   
 11  Education_PhD                 255347 non-null  bool   
 12  EmploymentType_Part-time      255347 non-nul

Splitting Dataset

In [19]:
X = df_encoded.drop('Default', axis=1)
y = df_encoded['Default']

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y )

Logistic Regression

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
#Scaling data
scaler = StandardScaler()
numeric_cols = X_train.select_dtypes(include='number').columns.tolist()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [ ]:
log_reg = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
log_reg.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [ ]:
y_pred_lr = log_reg.predict(X_test_scaled)

In [ ]:
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.6762874485999608
[[30390 14749]
 [ 1783  4148]]
              precision    recall  f1-score   support

           0       0.94      0.67      0.79     45139
           1       0.22      0.70      0.33      5931

    accuracy                           0.68     51070
   macro avg       0.58      0.69      0.56     51070
weighted avg       0.86      0.68      0.73     51070



Logistic Regression with SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler

In [ ]:
sm = SMOTE(random_state=42)
X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)

In [ ]:
X_train_sm.shape, y_train_sm.shape

((361110, 23), (361110,))

In [ ]:
numeric_cols = X_train.select_dtypes(include='number').columns.tolist()
scaler = StandardScaler()
X_train_sm_scaled = X_train_sm.copy()
X_test_scaled = X_test.copy()

X_train_sm_scaled[numeric_cols] = scaler.fit_transform(X_train_sm[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])


In [ ]:
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_sm_scaled, y_train_sm)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
y_pred = lr.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression Accuracy: 0.8032112786371647
[[39308  5831]
 [ 4219  1712]]
              precision    recall  f1-score   support

           0       0.90      0.87      0.89     45139
           1       0.23      0.29      0.25      5931

    accuracy                           0.80     51070
   macro avg       0.57      0.58      0.57     51070
weighted avg       0.82      0.80      0.81     51070



Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt = DecisionTreeClassifier(random_state=42,class_weight='balanced')
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

In [ ]:
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.8169179557470139
[[40525  4614]
 [ 4736  1195]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90     45139
           1       0.21      0.20      0.20      5931

    accuracy                           0.82     51070
   macro avg       0.55      0.55      0.55     51070
weighted avg       0.82      0.82      0.82     51070



Decision Tree with SMOTE

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_sm_scaled, y_train_sm)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred_dt = dt.predict(X_test_scaled)

In [ ]:
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7663794791462698
[[37384  7755]
 [ 4176  1755]]
              precision    recall  f1-score   support

           0       0.90      0.83      0.86     45139
           1       0.18      0.30      0.23      5931

    accuracy                           0.77     51070
   macro avg       0.54      0.56      0.54     51070
weighted avg       0.82      0.77      0.79     51070



Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)


RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [ ]:
y_proba = rf.predict_proba(X_test)[:, 1]
threshold = 0.10
y_pred_thresh = (y_proba >= threshold).astype(int)

In [ ]:
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.8848834932445663
[[45101    38]
 [ 5841    90]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     45139
           1       0.70      0.02      0.03      5931

    accuracy                           0.88     51070
   macro avg       0.79      0.51      0.48     51070
weighted avg       0.86      0.88      0.83     51070



Random Forest with SMOTE

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train_sm_scaled, y_train_sm)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
y_pred_rf = rf.predict(X_test_scaled)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.8688662619933425
[[43671  1468]
 [ 5229   702]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93     45139
           1       0.32      0.12      0.17      5931

    accuracy                           0.87     51070
   macro avg       0.61      0.54      0.55     51070
weighted avg       0.83      0.87      0.84     51070



XG Boost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
#Computing scale_pos_weight
neg = y_train.value_counts()[0]   # non-default
pos = y_train.value_counts()[1]   # default
scale = neg / pos

print("scale_pos_weight:", scale)


scale_pos_weight: 7.61128909872692


In [ ]:
xgb = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    scale_pos_weight=scale,
    learning_rate=0.05,
    max_depth=6,
    n_estimators=300,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
y_pred = xgb.predict(X_test)

In [ ]:
print("\n XGBoost Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


 XGBoost Accuracy: 0.7074995104758175
[[32189 12950]
 [ 1988  3943]]
              precision    recall  f1-score   support

           0       0.94      0.71      0.81     45139
           1       0.23      0.66      0.35      5931

    accuracy                           0.71     51070
   macro avg       0.59      0.69      0.58     51070
weighted avg       0.86      0.71      0.76     51070



XG Boost with SMOTE

In [ ]:
import xgboost as xgb

In [ ]:
xgb_model = xgb.XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb_model.fit(X_train_sm_scaled, y_train_sm)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [08:26:16] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
y_pred_xgb = xgb_model.predict(X_test_scaled)
print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

XGBoost Accuracy: 0.8692578813393381
[[43467  1672]
 [ 5005   926]]
              precision    recall  f1-score   support

           0       0.90      0.96      0.93     45139
           1       0.36      0.16      0.22      5931

    accuracy                           0.87     51070
   macro avg       0.63      0.56      0.57     51070
weighted avg       0.83      0.87      0.85     51070



Almost all traditional models function slightly or much better with SMOTE

ANN

Model 1

In [21]:
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [22]:
sm = SMOTE(random_state=42)
X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)

In [23]:
numeric_cols = X.select_dtypes(include="number").columns.tolist()

scaler = StandardScaler()

X_train_sm_scaled = X_train_sm.copy()
X_test_scaled = X_test.copy()

X_train_sm_scaled[numeric_cols] = scaler.fit_transform(X_train_sm[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])


In [24]:
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Dense(128, activation='relu', input_dim=X_train_sm_scaled.shape[1]),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu'),
    layers.BatchNormalization(),

    layers.Dense(1, activation='sigmoid')
])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [26]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [ ]:
history = model.fit(
    X_train_sm_scaled,
    y_train_sm,
    validation_split=0.2,
    epochs=40,
    batch_size=256,      # large batch for speed
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - accuracy: 0.8091 - loss: 0.4164 - val_accuracy: 0.8636 - val_loss: 0.2375
Epoch 2/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8629 - loss: 0.3212 - val_accuracy: 0.8744 - val_loss: 0.2158
Epoch 3/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8724 - loss: 0.3060 - val_accuracy: 0.8791 - val_loss: 0.1933
Epoch 4/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8759 - loss: 0.2972 - val_accuracy: 0.8830 - val_loss: 0.1907
Epoch 5/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8792 - loss: 0.2923 - val_accuracy: 0.8853 - val_loss: 0.1828
Epoch 6/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8766 - loss: 0.2953 - val_accuracy: 0.8868 - val_loss: 0.1846
Epoch 7/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8805 - loss: 0.2897 - val_accuracy: 0.8862 - val_loss: 0.1819
Epoch 8/40
1129/1129 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8801 - loss: 0.2886 -

In [ ]:
y_pred = (model.predict(X_test_scaled) > 0.5).astype(int)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("ANN Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


1596/1596 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step
ANN Accuracy: 0.7498923046798511
[[37517  7622]
 [ 5151   780]]
              precision    recall  f1-score   support

           0       0.88      0.83      0.85     45139
           1       0.09      0.13      0.11      5931

    accuracy                           0.75     51070
   macro avg       0.49      0.48      0.48     51070
weighted avg       0.79      0.75      0.77     51070



Model 2

In [27]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_sm),
    y=y_train_sm
)
class_weights = {i: w for i, w in enumerate(class_weights)}

In [28]:
from tensorflow.keras import layers, models, optimizers

model1 = models.Sequential([
    layers.Dense(128, activation='relu', input_dim=X_train_sm_scaled.shape[1]),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu'),
    layers.BatchNormalization(),

    layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model1.compile(
    optimizer=optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [ ]:
history = model1.fit(
    X_train_sm_scaled, y_train_sm,
    validation_data=(X_test_scaled, y_test),
    epochs=30,
    batch_size=256,
    verbose=1,
    class_weight=class_weights
)

Epoch 1/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.8229 - loss: 0.3856 - val_accuracy: 0.8605 - val_loss: 0.3530
Epoch 2/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8735 - loss: 0.2871 - val_accuracy: 0.8724 - val_loss: 0.3371
Epoch 3/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8800 - loss: 0.2735 - val_accuracy: 0.8733 - val_loss: 0.3377
Epoch 4/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8821 - loss: 0.2692 - val_accuracy: 0.8678 - val_loss: 0.3430
Epoch 5/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8828 - loss: 0.2656 - val_accuracy: 0.8676 - val_loss: 0.3391
Epoch 6/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8839 - loss: 0.2649 - val_accuracy: 0.8655 - val_loss: 0.3436
Epoch 7/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8849 - loss: 0.2623 - val_accuracy: 0.8693 - val_loss: 0.3437
Epoch 8/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8844 - loss: 0.2630 -

In [ ]:
y_pred_proba = model1.predict(X_test_scaled)
y_pred = (y_pred_proba > 0.3).astype(int)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("ANN Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

1596/1596 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step
ANN Accuracy: 0.8109261797532799
[[39066  6073]
 [ 3583  2348]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.89     45139
           1       0.28      0.40      0.33      5931

    accuracy                           0.81     51070
   macro avg       0.60      0.63      0.61     51070
weighted avg       0.84      0.81      0.82     51070



Model 3

In [29]:
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_sm),
    y=y_train_sm
)
class_weights = {i: w for i, w in enumerate(class_weights)}


In [30]:
X_train_sm_scaled.head()

Age    Income  LoanAmount  CreditScore  MonthsEmployed  \
0  0.334970 -1.020933    1.597630     0.383801       -1.130409   
1  0.548817  1.394074   -0.966215    -0.499787        1.977920   
2  0.477535  0.552918   -1.803341     1.022703        1.636004   
3  0.121124 -1.044878   -1.535172    -1.519311       -1.658825   
4 -1.447082  0.534479    1.606677    -1.696029        0.579172   

   NumCreditLines  InterestRate  DTIRatio  Education_High School  \
0       -0.361802     -1.610531  1.613174                   True   
1        0.595652      0.029031 -0.074642                  False   
2        0.595652     -1.466054  1.191220                   True   
3        0.595652      0.608559  1.191220                  False   
4        0.595652      0.796866 -0.262177                  False   

   Education_Master's  ...  EmploymentType_Unemployed  MaritalStatus_Married  \
0               False  ...                       True                   True   
1               False  ...                      False                   True   
2               False  ...                      False                  False   
3               False  ...                      False                   True   
4               False  ...                      False                  False   

   MaritalStatus_Single  HasMortgage_Yes  HasDependents_Yes  \
0                 False            False               True   
1                 False             True               True   
2                  True             True               True   
3                 False            False               True   
4                 False            False              False   

   LoanPurpose_Business  LoanPurpose_Education  LoanPurpose_Home  \
0                 False                  False             False   
1                 False                  False             False   
2                  True                  False             False   
3                 False                   True             False   
4                 False                  False             False   

   LoanPurpose_Other  HasCoSigner_Yes  
0              False            False  
1               True             True  
2              False             True  
3              False            False  
4              False             True  

[5 rows x 23 columns]

In [31]:


model2 = models.Sequential([
    layers.Dense(256, input_dim=X_train_sm_scaled.shape[1]),
    layers.LeakyReLU(alpha=0.1),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(128),
    layers.LeakyReLU(alpha=0.1),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(64),
    layers.LeakyReLU(alpha=0.1),
    layers.BatchNormalization(),
    layers.Dropout(0.2),

    layers.Dense(32, activation='relu'),
    layers.BatchNormalization(),

    layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(


In [32]:
model2.compile(
    optimizer=optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [33]:
history2 = model2.fit(
    X_train_sm_scaled, y_train_sm,
    validation_data=(X_test_scaled, y_test),
    epochs=30,
    batch_size=256,
    verbose=1,
    class_weight=class_weights
)

Epoch 1/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 18s 10ms/step - accuracy: 0.8328 - loss: 0.3640 - val_accuracy: 0.8580 - val_loss: 0.3577
Epoch 2/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.8757 - loss: 0.2821 - val_accuracy: 0.8672 - val_loss: 0.3410
Epoch 3/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 15s 11ms/step - accuracy: 0.8804 - loss: 0.2712 - val_accuracy: 0.8672 - val_loss: 0.3391
Epoch 4/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.8824 - loss: 0.2669 - val_accuracy: 0.8593 - val_loss: 0.3507
Epoch 5/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.8834 - loss: 0.2646 - val_accuracy: 0.8693 - val_loss: 0.3429
Epoch 6/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 15s 11ms/step - accuracy: 0.8846 - loss: 0.2634 - val_accuracy: 0.8656 - val_loss: 0.3475
Epoch 7/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.8854 - loss: 0.2622 - val_accuracy: 0.8599 - val_loss: 0.3552
Epoch 8/30
1411/1411 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.8858 -

In [34]:
import numpy as np
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix, classification_report

# Predicting probabilities
y_pred_proba = model2.predict(X_test_scaled)

# Threshold sweep from 0.1 to 0.9
thresholds = np.arange(0.1, 0.91, 0.05)
results = []

for t in thresholds:
    y_pred_thresh = (y_pred_proba > t).astype(int)
    acc = accuracy_score(y_test, y_pred_thresh)
    recall1 = recall_score(y_test, y_pred_thresh)  # Recall of class 1
    f1 = f1_score(y_test, y_pred_thresh)
    results.append((t, acc, recall1, f1))

# Convert results to array for easy viewing
results = np.array(results, dtype=float)

# Print all thresholds and metrics
print("Threshold | Accuracy | Class 1 Recall | F1-score")
for row in results:
    print(f"{row[0]:.2f}       | {row[1]:.3f}   | {row[2]:.3f}         | {row[3]:.3f}")

# Find threshold with highest class 1 recall without dropping accuracy too much
best_idx = np.argmax(results[:,2])  # prioritize class 1 recall
best_threshold = results[best_idx,0]
print(f"\nBest threshold for max class 1 recall: {best_threshold}")

# Final predictions with optimal threshold
y_pred_optimal = (y_pred_proba > best_threshold).astype(int)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_optimal))
print("\nClassification Report:\n", classification_report(y_test, y_pred_optimal))


1596/1596 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
Threshold | Accuracy | Class 1 Recall | F1-score
0.10       | 0.513   | 0.837         | 0.285
0.15       | 0.643   | 0.717         | 0.318
0.20       | 0.710   | 0.616         | 0.331
0.25       | 0.760   | 0.522         | 0.336
0.30       | 0.802   | 0.420         | 0.329
0.35       | 0.827   | 0.348         | 0.319
0.40       | 0.846   | 0.280         | 0.296
0.45       | 0.858   | 0.216         | 0.262
0.50       | 0.867   | 0.162         | 0.221
0.55       | 0.873   | 0.114         | 0.173
0.60       | 0.876   | 0.083         | 0.135
0.65       | 0.879   | 0.057         | 0.099
0.70       | 0.881   | 0.034         | 0.062
0.75       | 0.883   | 0.021         | 0.040
0.80       | 0.884   | 0.011         | 0.022
0.85       | 0.884   | 0.002         | 0.005
0.90       | 0.884   | 0.001         | 0.001

Best threshold for max class 1 recall: 0.1

Confusion Matrix:
 [[21213 23926]
 [  969  4962]]

Classification Report:
               precision

In [35]:
# Set optimal threshold
optimal_threshold = 0.25

# Predict class labels using the optimal threshold
y_pred_optimal = (model2.predict(X_test_scaled) > optimal_threshold).astype(int)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred_optimal)
print("Confusion Matrix:\n", cm)

# Classification Report
cr = classification_report(y_test, y_pred_optimal)
print("\nClassification Report:\n", cr)


1596/1596 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step
Confusion Matrix:
 [[35735  9404]
 [ 2836  3095]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.79      0.85     45139
           1       0.25      0.52      0.34      5931

    accuracy                           0.76     51070
   macro avg       0.59      0.66      0.59     51070
weighted avg       0.85      0.76      0.79     51070



Streamlit app

In [36]:
# Save the trained model2
model2.save('model2.h5')


In [37]:
import pickle

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [38]:
from google.colab import files

files.download('model2.h5')
files.download('scaler.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>